### PR TITLE
Three (mostly) cosmetic commits

### PR DESCRIPTION
**Pull request by RoPP**

### CODE REVIEW

**Comment by jocelynj** [comment]
I don't really like the commit that move all host config to inventories/production, as it adds a new level of hierarchy. Is there a reason to do this ?

Note that the first layout on http://docs.ansible.com/ansible/latest/playbooks_best_practices.html doesn't use inventories/production - it is only the alternative one.

**Comment by jocelynj** [comment]
I like the README changes on the last commit, but the path to hosts doesn't correspond to master :)

**Comment by RoPP** [comment]
I've remove the location modification of host files (for now).
This modification helps to have multiples env. I'll try to implements this by keeping the first directory layout. Then, push another PR.

**Comment by jocelynj** [comment]
Thanks, I've pushed the README change too !

**Pull request merged**
